@echo off
echo Resetting virtual environment to fix corruption...
if exist venv (
    rmdir /s /q venv
)
echo Creating virtual environment...
python -m venv venv
call venv\Scripts\activate.bat
echo Upgrading pip, setuptools, and libraries...
python -m pip install --upgrade pip setuptools google-genai yt-dlp
echo Installing dependencies...
pip install -r requirements.txt
echo Starting server...
python server.py
pause
